# Generated by Django 4.1.1 on 2022-09-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_entries', to='diary.folder'),
        ),
    ]
